application/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'application'

urlpatterns = [
    # path('', views.index, name="index"),
    path('', views.home, name="home"),
    path('category/<int:id>', views.category, name="category"),
    path('products/<int:id>', views.detail, name="products"),
    path('sign-up/', views.sign_up, name="sign_up"),
    path('sign-in/', views.sign_in, name="sign_in"),
    path('all_categories', views.all_categories, name='all_categories'),
    path('all-categories/', views.all_categories, name='all-categories'),
    path('sign-out', views.sign_out, name='sign_out'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('profile/', views.profile, name='profile'),
    path('all-products/', views.all_products, name='all-products'),
    path('mark-as-favorite', views.mark_as_favorite, name="mark-as-favorite"),
    path('get-favorites', views.get_favorites, name="get-favorites"),
    # path('signup', views.signup, name="signup"),
    # path('login', views.login, name="login"),
    # path('logout', views.logout, name="logout"),
]

urlpatterns = urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
]

templates/inc/base.html
{% load static %}
{% include 'inc/head.inc.html' %}
{% include 'inc/navbar.inc.html' %}
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/inc/features.html
{% load static %}
<div class="row our-features-box">
    <div class="container">
      <ul>
        <li>
          <div class="feature-box">
            <div class="icon-truck"></div>
            <div class="content-blocks">We ship worldwide</div>
          </div>
        </li>
        <li>
          <div class="feature-box">
            <div class="icon-support"></div>
            <div class="content-blocks">call
              +1 800 789 0000</div>
          </div>
        </li>
        <li>
          <div class="feature-box">
            <div class="icon-money"></div>
            <div class="content-blocks">Money Back Guarantee</div>
          </div>
        </li>
        <li>
          <div class="feature-box">
            <div class="icon-return"></div>
            <div class="content">30 days return</div>
          </div>
        </li>

      </ul>
    </div>
  </div>

templates/inc/head.inc.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Application</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  
    <!-- icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- <script src="{% static 'matrix/test/utils.js' %}"></script> -->


    <base href="http://127.0.0.1:8000/">

    <style>
        .my-form {
            text-align: center;
            border: solid 1px #cccccc;
            border-radius: 5px;
            padding: 50px;
        }

        select { 
            padding:10px;
            width: 10em 
        }

        .field {
            height: 50px;
            width: 350px;
            margin: 20px 0px;
            font-size: 11pt;
            padding: 8px 15px;
            border: 1px solid #cccccc;
            border-radius: 4px;
        }

        .profile {
            background-color: #ffffff;
            border-radius: 5px;
            text-align: center;
            border: solid 1px #cccccc;
        }


        @media only screen and (max-width: 500px) {
            .abc{
            padding-right: 40px;
            }

            .my-form {
                padding: 0px;
                width: 100%;
                border: none;
                margin-left: 20px;
            }
            
            .field {
                width: 100%;
            }

        }
    </style>

</head>

templates/inc/main_base.html
{% load static %}
{% load mathfilters %}
<!DOCTYPE html>
<html lang="en">

{% include 'inc/main_head.html' %}



<body class="cnt-home">
    {% include 'inc/main_navbar.html' %}

    {% block content %}
    {% endblock content %}

    {% include 'inc/main_footer.html' %}
</body>

<!-- JavaScripts placed at the end of the document so the pages load faster -->
<script src="{% static 'assets/js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-hover-dropdown.min.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/echo.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.easing-1.3.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-slider.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.rateit.min.js' %}"></script>
<script src="{% static 'assets/js/lightbox.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>


</html>

templates/inc/main_footer.html
{% load static %}

<!-- ============================================================= FOOTER ============================================================= -->
  <footer id="footer" class="footer color-bg">
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="address-block">

              <!-- /.module-heading -->

              <div class="module-body">
                <ul class="toggle-footer">
                  <li class="media">
                    <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i
                          class="fa fa-map-marker fa-stack-1x fa-inverse"></i> </span> </div>
                    <div class="media-body">
                      <p>ThemesGround, 789 Main rd, Anytown, CA 12345 USA</p>
                    </div>
                  </li>
                  <li class="media">
                    <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i
                          class="fa fa-mobile fa-stack-1x fa-inverse"></i> </span> </div>
                    <div class="media-body">
                      <p> + (888) 123-4567 / + (888) 456-7890</p>
                    </div>
                  </li>
                  <li class="media">
                    <div class="pull-left"> <span class="icon fa-stack fa-lg"> <i
                          class="fa fa-envelope fa-stack-1x fa-inverse"></i> </span> </div>
                    <div class="media-body"> <span><a href="#">marazzo@themesground.com</a></span> </div>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /.module-body -->
          </div>
          <!-- /.col -->

          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="module-heading">
              <h4 class="module-title">Customer Service</h4>
            </div>
            <!-- /.module-heading -->

            <div class="module-body">
              <ul class='list-unstyled'>
                <li class="first"><a href="#" title="Contact us">My Account</a></li>
                <li><a href="#" title="About us">Order History</a></li>
                <li><a href="#" title="faq">FAQ</a></li>
                <li><a href="#" title="Popular Searches">Specials</a></li>
                <li class="last"><a href="#" title="Where is my order?">Help Center</a></li>
              </ul>
            </div>
            <!-- /.module-body -->
          </div>
          <!-- /.col -->

          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="module-heading">
              <h4 class="module-title">Corporation</h4>
            </div>
            <!-- /.module-heading -->

            <div class="module-body">
              <ul class='list-unstyled'>
                <li class="first"><a title="Your Account" href="#">About us</a></li>
                <li><a title="Information" href="#">Customer Service</a></li>
                <li><a title="Addresses" href="#">Company</a></li>
                <li><a title="Addresses" href="#">Investor Relations</a></li>
                <li class="last"><a title="Orders History" href="#">Advanced Search</a></li>
              </ul>
            </div>
            <!-- /.module-body -->
          </div>
          <!-- /.col -->

          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="module-heading">
              <h4 class="module-title">Why Choose Us</h4>
            </div>
            <!-- /.module-heading -->

            <div class="module-body">
              <ul class='list-unstyled'>
                <li class="first"><a href="#" title="About us">Shopping Guide</a></li>
                <li><a href="#" title="Blog">Blog</a></li>
                <li><a href="#" title="Company">Company</a></li>
                <li><a href="#" title="Investor Relations">Investor Relations</a></li>
                <li class=" last"><a href="contact-us.html" title="Suppliers">Contact Us</a></li>
              </ul>
            </div>
            <!-- /.module-body -->
          </div>
        </div>
      </div>
    </div>
    <div class="copyright-bar">
      <div class="container">
        <div class="col-xs-12 col-sm-4 no-padding social">
          <ul class="link">
            <li class="fb pull-left"><a target="_blank" rel="nofollow" href="#" title="Facebook"></a></li>
            <li class="tw pull-left"><a target="_blank" rel="nofollow" href="#" title="Twitter"></a></li>
            <li class="googleplus pull-left"><a target="_blank" rel="nofollow" href="#" title="GooglePlus"></a></li>
            <li class="rss pull-left"><a target="_blank" rel="nofollow" href="#" title="RSS"></a></li>
            <li class="pintrest pull-left"><a target="_blank" rel="nofollow" href="#" title="PInterest"></a></li>
            <li class="linkedin pull-left"><a target="_blank" rel="nofollow" href="#" title="Linkedin"></a></li>
            <li class="youtube pull-left"><a target="_blank" rel="nofollow" href="#" title="Youtube"></a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 no-padding copyright"><a target="_blank"
            href="https://www.templateshub.net">Templates Hub</a> </div>
        <div class="col-xs-12 col-sm-4 no-padding">
          <div class="clearfix payment-methods">
            <ul>
              <li><img src="{% static 'assets/images/payments/1.png' %}" alt=""></li>
              <li><img src="{% static 'assets/images/payments/2.png' %}" alt=""></li>
              <li><img src="{% static 'assets/images/payments/3.png' %}" alt=""></li>
              <li><img src="{% static 'assets/images/payments/4.png' %}" alt=""></li>
              <li><img src="{% static 'assets/images/payments/5.png' %}" alt=""></li>
            </ul>
          </div>
          <!-- /.payment-methods -->
        </div>
      </div>
    </div>
  </footer>

templates/inc/main_head.html
{% load static %}
<head>
    <!-- Meta -->
    <base href="http://syedmaazhassan.pythonanywhere.com/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keywords" content="MediaCenter, Template, eCommerce">
    <meta name="robots" content="all">
    <title>Marazzo premium HTML5 & CSS3 Template</title>
  
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
  
    <!-- Customizable CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/blue.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.transitions.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/rateit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

    <!-- Icons/Glyphs -->
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom_css.css' %}">
  
  
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Barlow:200,300,300i,400,400i,500,500i,600,700,800"
      rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,800'
      rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">


  
</head>
  

templates/inc/main_navbar.html
{% load static %}

<header class="header-style-1">

    <!-- ============================================== TOP MENU ============================================== -->
    <div class="top-bar animate-dropdown">
      <div class="container">
        <div class="header-top-inner">
          <div class="cnt-account">
            <ul style="margin-top: 1.8rem;" class="list-unstyled">
            <li class="check"><a href="{% url 'application:all-categories' %}"><span class="menu-link">All categories</span></a></li>  
              <li class="check"><a href="{% url 'application:all-products' %}"><span class="menu-link">All products</span></a></li>
              {% if user.is_authenticated %}
              <li class="wishlist"><a href="{% url 'application:wishlist' %}"><span class="menu-link">My Wishlist</span></a></li>
              <li class="check"><a href="{% url 'application:profile' %}"><span class="menu-link">Profile</span></a></li>
              <li class="login"><a href="{% url 'application:sign_out' %}"><span class="menu-link">Log Out</span></a>
              </li>

              {% else %}
              <li class="login"><a href="{% url 'application:sign_in' %}"><span class="menu-link">Log In</span></a></li>
              <li class="login"><a href="{% url 'application:sign_up' %}"><span class="menu-link">Sign Up</span></a>
              </li>

              {% endif %}


            </ul>
          </div>
          <!-- /.cnt-account -->

          <!-- <div class="cnt-block">
            <ul class="list-unstyled list-inline">
              <li class="dropdown dropdown-small"> <a href="#" class="dropdown-toggle" data-hover="dropdown"
                  data-toggle="dropdown"><span class="value">USD </span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">USD</a></li>
                  <li><a href="#">INR</a></li>
                  <li><a href="#">GBP</a></li>
                </ul>
              </li>
              <li class="dropdown dropdown-small lang"> <a href="#" class="dropdown-toggle" data-hover="dropdown"
                  data-toggle="dropdown"><span class="value">English </span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">English</a></li>
                  <li><a href="#">French</a></li>
                  <li><a href="#">German</a></li>
                </ul>
              </li>
            </ul> -->
          <!-- /.list-unstyled -->
          <!-- </div> -->
          <!-- /.cnt-cart -->
          <div class="clearfix"></div>
        </div>
        <!-- /.header-top-inner -->
      </div>
      <!-- /.container -->
    </div>
    <!-- /.header-top -->
    <!-- ============================================== TOP MENU : END ============================================== -->
    <div class="main-header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-3 logo-holder">
            <!-- ============================================================= LOGO ============================================================= -->
            <div class="logo"> <a href="{% url 'application:home' %}"> <img src="{% static 'assets/images/logo.png' %}" alt="logo"> </a>
            </div>
            <!-- /.logo -->
            <!-- ============================================================= LOGO : END ============================================================= -->
          </div>
          <!-- /.logo-holder -->

          <div class="col-lg-7 col-md-6 col-sm-8 col-xs-12 top-search-holder">
            <!-- /.contact-row -->
            <!-- ============================================================= SEARCH AREA ============================================================= -->
            <div class="search-area">
              <form>
                <div class="control-group">
                  <ul class="categories-filter animate-dropdown">
                    <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown"
                        href="{% url 'application:all_categories' %}">Categories <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu">
                        {% for category in categories %}
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="{% url 'application:category' category.id %}">
                                    {{ category.name }} ({{ category.get_product_count }})
                                </a>
                            </li>
                        {% endfor %}
                      </ul>
                    </li>
                  </ul>
                  <input class="search-field" placeholder="Search here..." />
                  <a class="search-button" href="#"></a>
                </div>
              </form>
            </div>
            <!-- /.search-area -->
            <!-- ============================================================= SEARCH AREA : END ============================================================= -->
          </div>
          <!-- /.top-search-holder -->

          <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 animate-dropdown top-cart-row">
            <!-- ============================================================= SHOPPING CART DROPDOWN ============================================================= -->

            <div class="dropdown dropdown-cart"> <a href="{% url 'application:profile' %}" class="dropdown-toggle lnk-cart">
                <div class="items-cart-inner">
                  <div class="profile">
                      <i class="material-icons" style="font-size:40px;">account_circle</i>
                    <div class="total-price-basket"> <span class="lbl">Go to</span> <span
                        class="value">Profile</span> </div>
                  </div>
                </div>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <div class="cart-item product-summary">
                    <div class="row">
                      <div class="col-xs-4">
                        <div class="image"> <a href="detail.html"><img
                              src="{% static 'assets/images/products/p4.jpg' %}" alt=""></a>
                        </div>
                      </div>
                      <div class="col-xs-7">
                        <h3 class="name"><a href="index8a95.html?page-detail">Simple Product</a></h3>
                        <div class="price">$600.00</div>
                      </div>
                      <div class="col-xs-1 action"> <a href="#"><i class="fa fa-trash"></i></a> </div>
                    </div>
                  </div>
                  <!-- /.cart-item -->
                  <div class="clearfix"></div>
                  <hr>
                  <div class="clearfix cart-total">
                    <div class="pull-right"> <span class="text">Sub Total :</span><span class='price'>$600.00</span>
                    </div>
                    <div class="clearfix"></div>
                    <a href="checkout.html" class="btn btn-upper btn-primary btn-block m-t-20">Checkout</a>
                  </div>
                  <!-- /.cart-total-->

                </li>
              </ul>
              <!-- /.dropdown-menu-->
            </div>
            <!-- /.dropdown-cart -->

            <!-- ============================================================= SHOPPING CART DROPDOWN : END============================================================= -->
          </div>
          <!-- /.top-cart-row -->
        </div>
        <!-- /.row -->

      </div>
      <!-- /.container -->

    </div>
    <!-- /.main-header -->

    <!-- ============================================== NAVBAR ============================================== -->
    <div class="header-nav animate-dropdown">
      <div class="container">
        <div class="yamm navbar navbar-default" role="navigation">
          <div class="navbar-header">
            <button data-target="#mc-horizontal-menu-collapse" data-toggle="collapse" class="navbar-toggle collapsed"
              type="button">
              <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span
                class="icon-bar"></span> <span class="icon-bar"></span> </button>
          </div>
          <div class="nav-bg-class">
            <div class="navbar-collapse collapse" id="mc-horizontal-menu-collapse">
              <div class="nav-outer">
                <ul class="nav navbar-nav">
                  <li class="{% if home %}active{% endif %} dropdown"> <a href="{% url 'application:home' %}">Home</a> </li>
                  
                  {% for category in categories %}
                  {% if forloop.counter < 9 %}
                  <li class="{% if my_cat %}{% if my_cat.id == category.id %}active{% endif %}{% endif %} dropdown hidden-sm"> <a href="{% url 'application:category' category.id %}">{{ category.name }} ({{ category.get_product_count }})</a> </li>
                  {% endif %}
                  
                  {% endfor %}
                </ul>
                <!-- /.navbar-nav -->
                <div class="clearfix"></div>
              </div>
              <!-- /.nav-outer -->
            </div>
            <!-- /.navbar-collapse -->

          </div>
          <!-- /.nav-bg-class -->
        </div>
        <!-- /.navbar-default -->
      </div>
      <!-- /.container-class -->

    </div>
    <!-- /.header-nav -->
    <!-- ============================================== NAVBAR : END ============================================== -->

  </header>

templates/inc/navbar.inc.html
<div class="bg-info" style="height: 70px;">
    <div class="container pt-3">
        <i class="material-icons mb-3 float-left text-info bg-white mr-3" style="border-radius: 100%; padding:5px; font-size:30px; cursor: pointer;" title="Go back" onclick="window.history.back()">keyboard_arrow_left</i>
        {% if user.is_authenticated %}        
        <div class="float-left mt-1 text-white">
            <h4>Hi {{user.first_name}}</h4>
        </div>
        {% endif %}
        <div class="float-right">
            {% if user.is_authenticated %}
            <a href="logout">  

                <button type="button" style="border: solid 1px white; width: 100px;" class="mx-2 btn btn-info">Logout</button>

            </a>

            {% else %}
            <a href="login">

                <button type="button" style="border: solid 1px white; width: 100px;" class="mx-2 btn btn-info">Login</button>

            </a>

            <a href="signup">
                <button type="button" style="border: solid 1px white; width: 100px;" class="mx-2 btn btn-info">Sign Up</button>
            </a>
            {% endif %}
    
        </div>

    </div>        

</div>

templates/inc/product_list.html
{% load static %}
{% load mathfilters %}

<div class="row mb-5">
    {% for product in all_products %}

    <div class="col-sm-6 col-md-4 col-lg-3">

      <div class="item">

        <div class="products">

          <div class="product"  style="border-radius: 10px; box-shadow: 0 4px 8px 0 rgba(185, 185, 185, 0.2), 0 6px 20px 0 rgba(185, 185, 185, 0.2);">
            <div class="product-image">
              <div class="image">
                <a href="{% url 'application:products' product.id %}">
                  <img src="media/{{ product.get_primary_picture }}" style="border-radius: 10px 10px 0px 0px;" alt="">
                  <img src="media/{{ product.get_primary_picture }}" style="border-radius: 10px 10px 0px 0px;" alt="" class="hover-image">
                </a>
              </div>
              <!-- /.image -->

              <!-- <div class="tag new"><span>new</span></div> -->
            </div>
            <!-- /.product-image -->

            <div class="product-info text-left" >
              <div style="padding: 0px 10px 5px 10px;">

                <div class="row">
                    <div class="col-sm-9">
                        <a href="{% url 'application:products' product.id %}">
                            <h3 class="text-dark">{{ product.name }}</h3>
                        </a>
                    </div>

                    <div class="col-sm-3 d-flex align-items-center justify-content-center">
                        <div class="mt-5">
                            <i id="product_{{product.id}}" class="material-icons text-primary favorite_icon" onclick="toggle_favorite('{{ product.id }}')" style="margin-top: 20px;">favorite_border</i>
                        </div>
                     

                    </div>
                </div>
                
                <div class="description">
                    <p>
                    {{ product.tag_line }}
                    </p>
                </div>
                <div class="product-price"> <span class="price">$ {{ product.price }} </span> <span
                    class="price-before-discount">$ {{ product.price | addition:100 }}</span> </div>
                <!-- /.product-price -->
                </div>

            </div>
            <!-- /.product-info -->
            
            <!-- /.cart -->
          </div>

          <br>
          <!-- /.product -->

        </div>
        <!-- /.products -->
      </div>
      </a>
    </div>
    <!-- /.item -->
    {% endfor %}

    {% if not all_products %}
        <div class="col-sm-12 col-md-12 text-center col-lg-12 pb-0 mb-0">
            <div class="alert alert-warning" role="alert">
                No product exists right
            </div>
        </div>
    {% endif %}
    <!-- /.item -->
  </div>


  <script>
      function toggle_favorite(id) {
          let product_id = id;
          
          axios.get("{% url 'application:mark-as-favorite' %}", {
                params: {
                    id: product_id
                }
            })
            .then(function (response) {
                if (response.data.status) {
                    console.log(response.data);
                    if (response.data.auth){
                        if (response.data.favorite) {
                            $(`#product_${product_id}`).text("favorite");
                        }else{
                            $(`#product_${product_id}`).text("favorite_border");
                        }
                    }else{
                        if (confirm("Sign-in required to like the product, Do you want to sign-in now?")) {
                            window.location.href = "{% url 'application:sign_in' %}";
                        }
                    }

                }
            });
      }

      setTimeout(() => {
        axios
        .get("{% url 'application:get-favorites' %}")
        .then(function (response) {
            for (let i = 0; i < response.data.ids.length; i++) {
                let id = response.data.ids[i];
                $(`#product_${id}`).text("favorite");
            }
        });
      }, 500);
  </script>

templates/inc/side_category.html
<div class="side-menu animate-dropdown outer-bottom-xs">
    <div class="head"><i class="icon fa fa-align-justify fa-fw"></i><a style="color: rgb(77, 77, 77);"
        href="{% url 'application:all_categories' %}">Categories</a></div>
    <nav class="yamm megamenu-horizontal">
      <ul class="nav">
        {% for category in categories %}
        <li class="dropdown menu-item {% if my_cat %}{% if my_cat.id == category.id %}cat_active{% endif %}{% endif %}"> 
            <a href="{% url 'application:category' category.id %}">{{ category.name }} ({{ category.get_product_count }})</a>
          <!-- /.dropdown-menu -->
        </li>
        {% endfor %}
        <!-- /.menu-item -->

       
          <!-- ================================== MEGAMENU VERTICAL ================================== -->
        
        <!-- /.menu-item -->

      </ul>
      <!-- /.nav -->
    </nav>
    <!-- /.megamenu-horizontal -->
  </div>